### ISSUE TITLE
Allow overriding the KasmVNC Username

### ISSUE THREAD

**Issue by mmcclaskey** [kasmtech/workspaces-core-images#1]
Modify the following line to use a environmental variable for the KasmVNC username but default to kasm_user

https://github.com/kasmtech/workspaces-core-images/blob/0bb3cd1a0f0b39ef11fa2b63e1a6ab3cbac5ec75/src/common/startup_scripts/vnc_startup.sh#L177

**Comment by jerrywoo96** [comment]
So... what is the environment variable to change the login username? The docker run commands arn't updated to specify a different vnc user log in. And i cannot find any existing images that that mention this environment variable to change the vnc login username.

**Comment by traverseda** [comment]
I don't think this was actually completed, it was closed as completed after kasm didn't really do it.
