### ISSUE TITLE
How to run on plain HTTP

### ISSUE THREAD

**Issue by githubsaturn** [kasmtech/workspaces-core-images#2]
Looks like the initialization script is only running on a self signed HTTPS:
https://github.com/kasmtech/workspaces-core-images/blob/3a96329f08259aa5a5d5bf94435fcffec6e5e4a4/src/common/startup_scripts/vnc_startup.sh#L60

I have a separate server that handles reverse proxy and I want this VNC to run on plain HTTP. How can I disable this and just use the plain HTTP.

**Comment by mmcclaskey** [comment]
Remove the --sslOnly flag and KasmVNC will respond to both HTTP and HTTPS on the same port.

**Comment by mmcclaskey** [comment]
I need to elaborate a little. If you are running this container directly with docker run, that is fine. If you are running this within the full Kasm Workspaces stack, you cannot disable HTTPS on the containers. Those connections are proxied by NGINX which expects the upstream to be HTTPS.

**Comment by githubsaturn** [comment]
> I need to elaborate a little. If you are running this container directly with docker run, that is fine

That's the thing, I cannot remove `sslOnly` flag without rebuilding the image, right? This is not a command that I can control via Docker. I run:
```
docker run --rm  -it --shm-size=512m -p 6901:6901 -e VNC_PW=password  kasmweb/desktop:1.9.0
``` 

How can I disable sslOnly here?

**Comment by mmcclaskey** [comment]
You would have to build the image yourself after modifying the vnc_startup.sh script.

**Comment by ahkimkoo** [comment]
> 

You should also change /usr/share/kasmvnc/kasmvnc_defaults.yaml, line 25

require_ssl: true

to 

require_ssl: false

then docker restart container

> 

not work

**Comment by inmanturbo** [comment]
is this still not possible?

**Comment by fliot** [comment]
I do not know why, but depending the **Kubernetes** version (for the very same customized Kasmweb image),
On one version disabling https work immediately just removing "sslOnly" from the starting script,
And on the other, I also add to modify the kasmvnc_defaults.yaml file as mentioned...

At least, applying these 2 tricks work anywhere :-)

**Comment by StoiaCode** [comment]
So theres still no Official way to run this behind a reverse proxy that supplies SSL without self building images?
