### ISSUE TITLE
got Gamepad service failed

### ISSUE THREAD

**Issue by DaiZack** [kasmtech/workspaces-core-images#24]
tried sudo docker run --rm -it --shm-size=512m -p 6901:6901 -e VNC_PW=password kasmweb/core-ubuntu-bionic:1.12.0
on amd64 local ubuntu machine and a cloud arm64 server, both give the error:

```
/dockerstartup/vnc_startup.sh: line 263: kill: (80) - No such process
Gamepad Service Failed
```

**Comment by j-travis** [comment]
Can you still connect to session via your browser?

**Comment by DaiZack** [comment]
no I can't.

**Comment by j-travis** [comment]
I see the log messages you are referring too, but I can also connect to the running session
```
https://192.168.x.x:6901
```

There appears to be a problem when the service runs:
```
default:~$  /dockerstartup/gamepad/kasm_gamepad_server
[283] Error loading Python lib '/tmp/_MEIFTobzh/libpython3.8.so.1.0': dlopen: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/_MEIFTobzh/libpython3.8.so.1.0)
```

You can stop it from starting , and thus removing the error messages by setting the environment variable `KASM_SVC_GAMEPAD=0` during docker run.

```
sudo docker run --rm -it --shm-size=512m -p 6901:6901 -e VNC_PW=password -e KASM_SVC_GAMEPAD=0  kasmweb/core-ubuntu-bionic:1.12.0
```

The gamepad service isn't usable outside the Workspaces platform, so you can safely disable it, or run a new distro like ` kasmweb/core-ubuntu-focal:1.12.0`

**Comment by DaiZack** [comment]
both work for me, thank you
