### ISSUE TITLE
Kali linux root password

### ISSUE THREAD

**Issue by ghost** [kasmtech/workspaces-core-images#6]
hi, i want to login in kali as root to make update and install some additional tools, but i need password.
![image](https://user-images.githubusercontent.com/20506433/148417784-3c391962-915c-41cd-8517-a2a4797dba72.png)

**Comment by j-travis** [comment]
Hello, here you will find a write up and running the container as root, or installing sudo with a password you choose:
https://kasmweb.com/docs/latest/how_to/running_as_root.html

if you are running the container outside workspaces you can specify:
 `docker run --user root ....`
